export enum API_KEY {
  SEMESTER_LIST = 'SEMESTER_LIST',
  OPEN_COURSES_DEPARTMENT = 'OPEN_COURSES_DEPARTMENT',
  OPEN_COURSES = 'OPEN_COURSES',
  CURRENT_OPEN_SEMESTER = 'CURRENT_OPEN_SEMESTER',
  CURRENT_OPEN_SEMESTER_BY_DATE = 'CURRENT_OPEN_SEMESTER_BY_DATE',
}
