// Keys for the queries related to the Courses
export enum API_COURSE_QUERIES {
  STUDENTS_IN_COURSE = 'STUDENTS_IN_COURSE',
  TEACHERS_IN_COURSE = 'TEACHERS_IN_COURSE',
  GET_COURSE_LIST = 'GET_COURSE_LIST',
  GET_STUDENTS_IN_COURSE = 'GET_STUDENTS_IN_COURSE',
  GET_TEACHERS_IN_COURSE = 'GET_TEACHERS_IN_COURSE',
  ADD_TEACHERS_INTO_COURSE = 'ADD_TEACHERS_INTO_COURSE',
  ADD_STUDENTS_INTO_COURSE = 'ADD_STUDENTS_INTO_COURSE',
  REMOVE_TEACHERS_FROM_COURSE = 'REMOVE_TEACHERS_FROM_COURSE',
  REMOVE_STUDENTS_FROM_COURSE = 'REMOVE_STUDENTS_FROM_COURSE',
  UPLOAD_IMAGE_IN_COURSE = 'UPLOAD_IMAGE_IN_COURSE',
  UPLOAD_FILES_IN_COURSE = 'UPLOAD_FILES_IN_COURSE',
}
