export enum REGISTER_COURSE_API_KEY {
  REGISTER_COURSE = 'REGISTER_COURSE',
  GET_REGISTERED_COURSES = 'GET_REGISTERED_COURSES',
  GET_UNREGISTERED_COURSES = 'GET_UNREGISTERED_COURSES',
  GET_APPROVED_COURSES = 'GET_APPROVED_COURSES',
  ASSIGN_TEACHER = 'ASSIGN_TEACHER',
  REMOVE_TEACHER = 'REMOVE_TEACHER',
  APPROVE_REGISTRATIONS = 'APPROVE_COURSE',
  GET_ALL_REGISTRATIONS = 'GET_ALL_REGISTRATIONS',
  ASSIGN_TEACHER_ROLE = 'ASSIGN_TEACHER_ROLE',
}
