// Keys for the queries related to the Buildings and Rooms
export enum API_BUILDING_QUERIES {
  GET_ALL_BUILDINGS = 'GET_ALL_BUILDINGS',
  GET_BUILDING_BY_ID = 'GET_BUILDING_BY_ID',
  CREATE_BUILDING = 'CREATE_BUILDING',
  UPDATE_BUILDING = 'UPDATE_BUILDING',
  DELETE_BUILDING = 'DELETE_BUILDING',
  GET_ROOMS_BY_BUILDING = 'GET_ROOMS_BY_BUILDING',
  GET_ROOM_BY_ID = 'GET_ROOM_BY_ID',
  ADD_ROOM = 'ADD_ROOM',
  UPDATE_ROOM = 'UPDATE_ROOM',
  DELETE_ROOM = 'DELETE_ROOM',
}