export enum API_STUDENTS_QUERIES {
  STUDENTS_LIST = 'STUDENTS_LIST',
  STUDENT_BY_ID = 'STUDENT_BY_ID',
  STUDENT_INFO = 'student_info',
  REGISTER_COURSE = 'REGISTER_COURSE',
  REMOVE_REGISTERED_COURSE = 'REMOVE_REGISTERED_COURSE',
  REMOVE_STUDENT_FROM_COURSE = 'REMOVE_STUDENT_FROM_COURSE',
}
