export enum API_TEACHERS_QUERIES {
  TEACHERS_LIST = 'TEACHERS_LIST',
  TEACHER_BY_ID = 'TEACHER_BY_ID',
  TEACHER_BY_IDS = 'TEACHER_BY_IDS',
  TEACHER_HAVE_COURSE_IN_SEMESTER = 'TEACHER_HAVE_COURSE_IN_SEMESTER',
}
