export enum API_DEPARTMENT {
  DEPARTMENT_LIST = 'DEPARTMENT_LIST',
  DEPARTMENT_BY_ID = 'DEPARTMENT_BY_ID',
  COURSES_IN_DEPARTMENT = 'COURSES_IN_DEPARTMENT',
  BASE_COURSES_IN_DEPARTMENT = 'BASE_COURSES_IN_DEPARTMENT',
}
