export enum API_ATTENDANCE_QUERIES {
  CLASS_SESSION_BY_SESSION_ID = 'CLASS_SESSION_BY_SESSION_ID',
  TEACHER_CHECK_ATTENDANCE = 'TEACHER_CHECK_ATTENDANCE',
  CLASS_SESSION_BY_COURSE_ID = 'CLASS_SESSION_BY_COURSE_ID',
  CLASS_SESSION_BY_COURSE_ID_AND_DATE = 'CLASS_SESSION_BY_COURSE_ID_AND_DATE',
  TIME_SLOT_BY_TEACHER_AND_SEMESTER = 'TIME_SLOT_BY_TEACHER_AND_SEMESTER',
  DELETE_TIME_SLOT_BY_TEACHER_AND_TIME_SLOT_ID = 'DELETE_TIME_SLOT_BY_TEACHER_AND_TIME_SLOT_ID',
}

export enum DayOfWeek {
  SUNDAY = 'SUNDAY',
  MONDAY = 'MONDAY',
  TUESDAY = 'TUESDAY',
  WEDNESDAY = 'WEDNESDAY',
  THURSDAY = 'THURSDAY',
  FRIDAY = 'FRIDAY',
  SATURDAY = 'SATURDAY',
}
