export enum API_ATTENDANCE_QUERIES {
	CLASS_SESSION_BY_SESSION_ID = 'CLASS_SESSION_BY_SESSION_ID',
	TEACHER_CHECK_ATTENDANCE = 'TEACHER_CHECK_ATTENDANCE',
	CLASS_SESSION_BY_COURSE_ID = 'CLASS_SESSION_BY_COURSE_ID',
	CLASS_SESSION_BY_COURSE_ID_AND_DATE = 'CLASS_SESSION_BY_COURSE_ID_AND_DATE',
}

export enum DayOfWeek {
  SUNDAY = 'SUNDAY',
  MONDAY = 'MONDAY',
  TUESDAY = 'TUESDAY',
  WEDNESDAY = 'WEDNESDAY',
  THURSDAY = 'THURSDAY',
  FRIDAY = 'FRIDAY',
  SATURDAY = 'SATURDAY',
}
