export enum API_TIMETABLES_QUERIES {
  TIMETABLES_BY_COURSE_ID = 'TIMETABLES_BY_COURSE_ID',
  CALENDAR_BY_TEACHER_ID = 'CALENDAR_BY_TEACHER_ID',
  TIMETABLES_BY_STUDENT_ID = 'TIMETABLES_BY_STUDENT_ID',
}
